@coachToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhODMxMGRmMTIwMWRiODU1MTIwYzgzOCIsInJvbGUiOiJjb2FjaCIsImlhdCI6MTc4Njk3NDQ2MywiZXhwIjoxNzg3NTc5MjYzfQ.n01nuz4VbFS3GsmmsVVmHCHoOtbWQIJ8tbfVxgH7LGk

@playerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNzcyZTI2M2FiODAzNGI4Zjk1MTU4ZSIsInJvbGUiOiJwbGF5ZXIiLCJpYXQiOjE3ODY5NzQ1NjUsImV4cCI6MTc4NzU3OTM2NX0.7mk1NNqX9lUOzvG_cOngvf264CT6z1LOlGSn5L6rmrU 

@otherCoachToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNzc0MDY4NDI4N2JhOGVkMDUxMGZlNyIsInJvbGUiOiJjb2FjaCIsImlhdCI6MTc4NjIwMDE2OCwiZXhwIjoxNzg2ODA0OTY4fQ.qnPmPx_UevXplKPUag3-xLV0Jln2LiXM3aFpIt-Y9MY

@groupId = 6a8311231201db855120c839
@groupCode = 508568

# À remplir après création des événements
@eventId = 
@otherEventId = 


############################################################
# CREATE EVENT
############################################################

### Coach du groupe → 201
POST http://localhost:3000/groups/{{groupId}}/events
Content-Type: application/json
Cookie: token={{coachToken}}

{
  "name": "Entraînement U20",
  "date": "2026-08-18T18:00:00.000Z",
  "location": "Piscine municipale",
  "eventType": "training"
}

###

### Player → 403
POST http://localhost:3000/groups/{{groupId}}/events
Content-Type: application/json
Cookie: token={{playerToken}}

{
  "name": "Entraînement interdit",
  "date": "2026-08-20T18:00:00.000Z",
  "location": "Piscine municipale",
  "eventType": "training"
}

###

### Autre coach → 403
POST http://localhost:3000/groups/{{groupId}}/events
Content-Type: application/json
Cookie: token={{otherCoachToken}}

{
  "name": "Événement interdit",
  "date": "2026-08-20T18:00:00.000Z",
  "location": "Piscine municipale",
  "eventType": "training"
}

###

### Sans token → 401
POST http://localhost:3000/groups/{{groupId}}/events
Content-Type: application/json

{
  "name": "Test",
  "date": "2026-08-20T18:00:00.000Z",
  "location": "Piscine municipale",
  "eventType": "training"
}

###

### Nom vide → 400
POST http://localhost:3000/groups/{{groupId}}/events
Content-Type: application/json
Cookie: token={{coachToken}}

{
  "name": "",
  "date": "2026-08-20T18:00:00.000Z",
  "location": "Piscine municipale",
  "eventType": "training"
}

###

### Date passée → 400
POST http://localhost:3000/groups/{{groupId}}/events
Content-Type: application/json
Cookie: token={{coachToken}}

{
  "name": "Test",
  "date": "2020-01-01T18:00:00.000Z",
  "location": "Piscine municipale",
  "eventType": "training"
}

###

### Location vide → 400
POST http://localhost:3000/groups/{{groupId}}/events
Content-Type: application/json
Cookie: token={{coachToken}}

{
  "name": "Test",
  "date": "2026-08-20T18:00:00.000Z",
  "location": "",
  "eventType": "training"
}

###

### EventType invalide → 400
POST http://localhost:3000/groups/{{groupId}}/events
Content-Type: application/json
Cookie: token={{coachToken}}

{
  "name": "Test",
  "date": "2026-08-20T18:00:00.000Z",
  "location": "Piscine municipale",
  "eventType": "invalid"
}

###

### Groupe inexistant → 404
POST http://localhost:3000/groups/000000000000000000000000/events
Content-Type: application/json
Cookie: token={{coachToken}}

{
  "name": "Test",
  "date": "2026-08-20T18:00:00.000Z",
  "location": "Piscine municipale",
  "eventType": "training"
}


############################################################
# GET EVENTS
############################################################

### Coach du groupe → 200
GET http://localhost:3000/groups/{{groupId}}/events
Cookie: token={{coachToken}}

###

### Player membre → 200
GET http://localhost:3000/groups/{{groupId}}/events
Cookie: token={{playerToken}}

###

### Autre coach → 403
GET http://localhost:3000/groups/{{groupId}}/events
Cookie: token={{otherCoachToken}}

###

### Sans token → 401
GET http://localhost:3000/groups/{{groupId}}/events

###

### Groupe inexistant → 404
GET http://localhost:3000/groups/000000000000000000000000/events
Cookie: token={{playerToken}}


############################################################
# GET EVENT
############################################################

### Player membre → 200
GET http://localhost:3000/groups/{{groupId}}/events/{{eventId}}
Cookie: token={{playerToken}}

###

### Coach du groupe → 200
GET http://localhost:3000/groups/{{groupId}}/events/{{eventId}}
Cookie: token={{coachToken}}

###

### Autre coach → 403
GET http://localhost:3000/groups/{{groupId}}/events/{{eventId}}
Cookie: token={{otherCoachToken}}

###

### Sans token → 401
GET http://localhost:3000/groups/{{groupId}}/events/{{eventId}}

###

### Event inexistant → 404
GET http://localhost:3000/groups/{{groupId}}/events/000000000000000000000000
Cookie: token={{playerToken}}

###

### Event appartenant à un autre groupe → 404
GET http://localhost:3000/groups/{{groupId}}/events/{{otherEventId}}
Cookie: token={{playerToken}}


############################################################
# UPDATE EVENT
############################################################

### Coach du groupe → 200
PUT http://localhost:3000/groups/{{groupId}}/events/{{eventId}}
Content-Type: application/json
Cookie: token={{coachToken}}

{
  "name": "Entraînement U18 modifié",
  "date": "2026-08-21T18:00:00.000Z",
  "location": "Nouvelle piscine",
  "eventType": "training"
}

###

### Player → 403
PUT http://localhost:3000/groups/{{groupId}}/events/{{eventId}}
Content-Type: application/json
Cookie: token={{playerToken}}

{
  "name": "Modification interdite",
  "date": "2026-08-21T18:00:00.000Z",
  "location": "Piscine",
  "eventType": "training"
}

###

### Autre coach → 403
PUT http://localhost:3000/groups/{{groupId}}/events/{{eventId}}
Content-Type: application/json
Cookie: token={{otherCoachToken}}

{
  "name": "Modification interdite",
  "date": "2026-08-21T18:00:00.000Z",
  "location": "Piscine",
  "eventType": "training"
}

###

### Date passée → 400
PUT http://localhost:3000/groups/{{groupId}}/events/{{eventId}}
Content-Type: application/json
Cookie: token={{coachToken}}

{
  "name": "Test",
  "date": "2020-01-01T18:00:00.000Z",
  "location": "Piscine",
  "eventType": "training"
}

###

### EventType invalide → 400
PUT http://localhost:3000/groups/{{groupId}}/events/{{eventId}}
Content-Type: application/json
Cookie: token={{coachToken}}

{
  "name": "Test",
  "date": "2026-08-21T18:00:00.000Z",
  "location": "Piscine",
  "eventType": "invalid"
}

###

### Event d'un autre groupe → 404
PUT http://localhost:3000/groups/{{groupId}}/events/{{otherEventId}}
Content-Type: application/json
Cookie: token={{coachToken}}

{
  "name": "Tentative d'accès",
  "date": "2026-08-21T18:00:00.000Z",
  "location": "Piscine",
  "eventType": "training"
}

###

### Sans token → 401
PUT http://localhost:3000/groups/{{groupId}}/events/{{eventId}}
Content-Type: application/json

{
  "name": "Test",
  "date": "2026-08-21T18:00:00.000Z",
  "location": "Piscine",
  "eventType": "training"
}


############################################################
# DELETE EVENT
############################################################

### Player → 403
DELETE http://localhost:3000/groups/{{groupId}}/events/{{eventId}}
Cookie: token={{playerToken}}

###

### Autre coach → 403
DELETE http://localhost:3000/groups/{{groupId}}/events/{{eventId}}
Cookie: token={{otherCoachToken}}

###

### Event d'un autre groupe → 404
DELETE http://localhost:3000/groups/{{groupId}}/events/{{otherEventId}}
Cookie: token={{coachToken}}

###

### Sans token → 401
DELETE http://localhost:3000/groups/{{groupId}}/events/{{eventId}}

###

### Coach du groupe → 200
DELETE http://localhost:3000/groups/{{groupId}}/events/{{eventId}}
Cookie: token={{coachToken}}

###

### Event déjà supprimé → 404
DELETE http://localhost:3000/groups/{{groupId}}/events/{{eventId}}
Cookie: token={{coachToken}}
